import type {Metadata} from "next";
import "./globals.css";
import 'primeflex/primeflex.scss';



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body style={{"margin": "100px"}}>
        {children}
        </body>
        </html>
    );
}
