import type {Metadata} from "next";
// import "./globals.css";

import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/saga-blue/theme.css';

import 'primeicons/primeicons.css';
import 'primeflex/primeflex.min.css';





import {PrimeReactProvider} from 'primereact/api';

// import "primereact/resources/themes/lara-light-cyan/theme.css";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body style={{"margin": "100px"}}>
        <PrimeReactProvider >
            {children}
        </PrimeReactProvider>
        </body>
        </html>
    );
}
